name: Docker

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  PLATFORMS: linux/amd64
  #,linux/arm64

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        gcc-version: ['11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@1e95c1de343b5b0c23352d6417ee3e48d5bcd422
        with:
          cosign-release: 'v1.4.0'

#      # Add ARM emulation support
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # alpaqa build static ----------------------------------------------------

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-alpaqa-build-static
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/tttapa/alpaqa-build-static
          flavor: |
            latest=${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
            prefix=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }}-
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }},prefix=

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push-alpaqa-build-static
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          target: alpaqa-build-static
          build-args: |
            "GCC_VERSION=${{ matrix.gcc-version }}"
            "PYTHON_VERSION=${{ matrix.python-version }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alpaqa-build-static.outputs.tags }}
          labels: ${{ steps.meta-alpaqa-build-static.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ env.REGISTRY }}/tttapa/alpaqa-build-static@${{ steps.build-and-push-alpaqa-build-static.outputs.digest }}

      # alpaqa build -----------------------------------------------------------

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-alpaqa-build
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/tttapa/alpaqa-build
          flavor: |
            latest=${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
            prefix=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }}-
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }},prefix=

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push-alpaqa-build
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          target: alpaqa-build
          build-args: |
            "GCC_VERSION=${{ matrix.gcc-version }}"
            "PYTHON_VERSION=${{ matrix.python-version }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alpaqa-build.outputs.tags }}
          labels: ${{ steps.meta-alpaqa-build.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ env.REGISTRY }}/tttapa/alpaqa-build@${{ steps.build-and-push-alpaqa-build.outputs.digest }}

      # alpaqa docs ------------------------------------------------------------

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-alpaqa-docs
        if: ${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/tttapa/alpaqa-docs
          flavor: |
            latest=${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
            prefix=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }}-
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }},prefix=

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push-alpaqa-docs
        if: ${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          target: alpaqa-docs
          build-args: |
            "GCC_VERSION=${{ matrix.gcc-version }}"
            "PYTHON_VERSION=${{ matrix.python-version }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alpaqa-docs.outputs.tags }}
          labels: ${{ steps.meta-alpaqa-docs.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' && matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ env.REGISTRY }}/tttapa/alpaqa-docs@${{ steps.build-and-push-alpaqa-docs.outputs.digest }}

      # alpaqa test static -----------------------------------------------------

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-alpaqa-test-static
        if: ${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/tttapa/alpaqa-test-static
          flavor: |
            latest=${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
            prefix=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }}-
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }},prefix=

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push-alpaqa-test-static
        if: ${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          target: alpaqa-test-static
          build-args: |
            "GCC_VERSION=${{ matrix.gcc-version }}"
            "PYTHON_VERSION=${{ matrix.python-version }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alpaqa-test-static.outputs.tags }}
          labels: ${{ steps.meta-alpaqa-test-static.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' && matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ env.REGISTRY }}/tttapa/alpaqa-test-static@${{ steps.build-and-push-alpaqa-test-static.outputs.digest }}

      # alpaqa test ------------------------------------------------------------

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-alpaqa-test
        if: ${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/tttapa/alpaqa-test
          flavor: |
            latest=${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
            prefix=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }}-
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=gcc${{ matrix.gcc-version }}-py${{ matrix.python-version }},prefix=

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push-alpaqa-test
        if: ${{ matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          target: alpaqa-test
          build-args: |
            "GCC_VERSION=${{ matrix.gcc-version }}"
            "PYTHON_VERSION=${{ matrix.python-version }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alpaqa-test.outputs.tags }}
          labels: ${{ steps.meta-alpaqa-test.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' && matrix.gcc-version == '11' && matrix.python-version == '3.10' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ env.REGISTRY }}/tttapa/alpaqa-test@${{ steps.build-and-push-alpaqa-test.outputs.digest }}
